package main

import (
	// SQLite driver for greywallapi
	_ "modernc.org/sqlite"

	// Register connectors
	_ "github.com/greyhavenhq/greyproxy/internal/gostx/connector/direct"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/connector/forward"
	_ "github.com/greyhavenhq/greyproxy/internal/gostx/connector/http"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/connector/http2"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/connector/relay"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/connector/router"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/connector/serial"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/connector/sni"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/connector/socks/v4"
	_ "github.com/greyhavenhq/greyproxy/internal/gostx/connector/socks/v5"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/connector/ss"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/connector/ss/udp"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/connector/sshd"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/connector/tcp"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/connector/tunnel"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/connector/unix"

	// Register dialers
	_ "github.com/greyhavenhq/greyproxy/internal/gostx/dialer/direct"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/dialer/dtls"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/dialer/ftcp"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/dialer/grpc"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/dialer/http2"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/dialer/http2/h2"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/dialer/http3"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/dialer/http3/wt"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/dialer/icmp"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/dialer/kcp"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/dialer/mtcp"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/dialer/mtls"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/dialer/mws"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/dialer/obfs/http"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/dialer/obfs/tls"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/dialer/pht"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/dialer/quic"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/dialer/serial"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/dialer/ssh"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/dialer/sshd"
	_ "github.com/greyhavenhq/greyproxy/internal/gostx/dialer/tcp"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/dialer/tls"
	_ "github.com/greyhavenhq/greyproxy/internal/gostx/dialer/udp"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/dialer/unix"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/dialer/ws"

	// Register handlers
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/handler/api"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/handler/auto"
	_ "github.com/greyhavenhq/greyproxy/internal/gostx/handler/dns"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/handler/file"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/handler/forward/local"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/handler/forward/remote"
	_ "github.com/greyhavenhq/greyproxy/internal/gostx/handler/http"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/handler/http2"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/handler/http3"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/handler/metrics"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/handler/redirect/tcp"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/handler/redirect/udp"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/handler/relay"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/handler/router"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/handler/serial"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/handler/sni"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/handler/socks/v4"
	_ "github.com/greyhavenhq/greyproxy/internal/gostx/handler/socks/v5"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/handler/ss"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/handler/ss/udp"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/handler/sshd"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/handler/tap"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/handler/tun"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/handler/tungo"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/handler/tunnel"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/handler/unix"

	// Register listeners
	_ "github.com/greyhavenhq/greyproxy/internal/gostx/listener/dns"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/listener/dtls"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/listener/ftcp"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/listener/grpc"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/listener/http2"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/listener/http2/h2"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/listener/http3"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/listener/http3/h3"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/listener/http3/wt"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/listener/icmp"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/listener/kcp"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/listener/mtcp"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/listener/mtls"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/listener/mws"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/listener/obfs/http"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/listener/obfs/tls"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/listener/pht"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/listener/quic"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/listener/redirect/tcp"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/listener/redirect/udp"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/listener/rtcp"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/listener/rudp"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/listener/serial"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/listener/ssh"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/listener/sshd"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/listener/tap"
	_ "github.com/greyhavenhq/greyproxy/internal/gostx/listener/tcp"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/listener/tls"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/listener/tun"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/listener/tungo"
	_ "github.com/greyhavenhq/greyproxy/internal/gostx/listener/udp"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/listener/unix"
	// _ "github.com/greyhavenhq/greyproxy/internal/gostx/listener/ws"
)
